version: '3.8'

services:
  web:
    build: ./testapi
    #restart: always
    container_name: django_api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./testapi:/usr/src/testapi/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    #restart: always
    container_name: postgres_api
    env_file: .env
    #volumes:
    #  - ./dbdata:/
